name = "esmodule-example"
type = "javascript"
workers_dev = true
# account_id = "Or specified with process.env.CF_ACCOUNT_ID"
# zone_id = "Or specified with process.env.CF_ZONE_ID"
# route = "example.com/*"

[[kv_namespaces]]
binding = "CONTENT"
preview_id = "preview_id"
id = "id"

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build"
watch_dir = "./build/index.js"

[build.upload]
format = "modules"
dir = "./dist"
main = "./worker.mjs"

[durable_objects]
bindings = [{ name = "COUNTER", class_name = "Counter" }]

[workaholic]
source = "content"
binding = "CONTENT"
config = "./scripts/workaholic.ts"
