name = "remix-guide"
type = "javascript"
workers_dev = false
account_id = "c63d756a160ad09cd9a82553c77e9174"
zone_id = "e433232c2f0e3fddcd03a20251740130"
route = "remix.guide/*"
compatibility_date = "2021-11-22"

[[kv_namespaces]]
binding = "CONTENT"
preview_id = "b9abf9fff06846969b24a000214328f0"
id = "ac24beac98a54c2786c7605bbbabdbdc"

[site]
bucket = "./public"
entry-point = "."

[durable_objects]
bindings = [
  { name = "COUNTER", class_name = "Counter" },
  { name = "ENTRIES_DO", class_name = "Entries" },
]

[[migrations]]
tag = "v0.1"
new_classes = ["Counter"]

[build]
command = "npm run build"
watch_dir = "./build/index.js"

[build.upload]
format = "modules"
dir = "./dist"
main = "./worker.mjs"

[workaholic]
source = "content"
binding = "CONTENT"
config = "./scripts/workaholic.ts"
