name: Deploy
on:
  push:
    branches: main
jobs:
  deploy:
    name: ✨ Deploying to Cloudflare Workers
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-
            ${{ runner.OS }}-
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Code format check
        run: npx prettier --check .
      - name: Code linting
        run: npx eslint . --ext .js,.mjs,.ts,.tsx
      - name: Generate test data
        run: npx workaholic build content.json
      - name: Run tests
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        run: npx wrangler publish
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
